before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: "neckless"
    ldflags:
      - "-s -w -X main.Version='$(.Env.VERSION)' -X main.GitCommit=$(.Env.GITCOMMIT)"
#      - freebsd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - amd64
      - 386
      - arm64
    goarm:
      - 6
      - 7
    main: ./
    binary: neckless
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "neckless_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
