before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: "neckless"
    ldflags:
      - "-s -w -X main.Version='{{.Version}}' -X main.GitCommit={{.Commit}}"
#      - freebsd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - amd64
      - 386
      - arm64
    goarm:
      - 6
      - 7
    main: ./
    binary: neckless
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "neckless_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{.Arm}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
dockers:
- image_templates: ["ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APL2

- image_templates: ["ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-i386"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/i386
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APL2

- image_templates: ["ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APL2

- image_templates: ["ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-armv7"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mabels/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APL2

docker_manifests:
- name_template: ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-i386
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/mabels/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-i386
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/mabels/{{ .ProjectName }}:{{ .Version }}-arm64v8

