name: 'Setup Neckless'
description: 'Github Action provides the neckless tool'
inputs:
  version:
    description: 'the version of neckless'
    required: false
    default: 'v0.1.12'
  url: 
    description: 'base url to download'
    required: false
    default: 'https://github.com/mabels/neckless/releases/download'
  filename:
    description: 'filename of neckless'
    required: false
    default: 'neckless'
  os:
    description: 'os of neckless'
    required: false
  suffix:
    description: 'suffix of neckless'
    required: false
    default: '.tar.gz'
  cpu:
    description: 'cpu of neckless'
    required: false
#outputs:
#  tools: # id of output
#    description: 'tools are ready'
runs:
  using: 'node16'
  main: 'action/index.js'
