name: go-build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ARM64
            go: '1.14'
            path_name: neckless
            bin_name: neckless-linux-arm64
          - platform: ubuntu-latest
            go: '1.14'
            path_name: neckless
            bin_name: neckless-linux
          - platform: macos-latest
            go: '1.14'
            path_name: neckless
            bin_name: neckless-macos
          # - platform: windows-latest
          #   go: '1.14'
          #   path_name: neckless.exe
          #   bin_name: neckless-win.exe
    name: Build Go ${{ matrix.go }} ${{ matrix.platform }} neckless
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: |
          make test
          make build BIN_NAME=${{ matrix.bin_name }}
          if [ $(uname -p) = "x86_64" ]
          then
            echo $GITHUB_TOKEN | docker login docker.pkg.github.com/ -u mabels --password-stdin
            VERSION=$(shell git describe --tags HEAD)
            GITCOMMIT=$(shell git rev-list -1 HEAD)
            docker build -n docker.pkg.github.com//mabels/neckless/{{ matrix.bin_name }}:$GITCOMMIT .
            docker push docker.pkg.github.com//mabels/neckless/{{ matrix.bin_name }}:$GITCOMMIT
          fi
